### ISSUE TITLE
Indicator shows A+ on a site with an untrusted certificate

### ISSUE THREAD

**Issue by securedirective** [wolffc/sslgrade-chrome#1]
On a random website (https://admin.cbonews.gov/) that is listed by SSLlabs as 'T' for trust issues, your extension shows an A+.

**Comment by wolffc** [comment]
Thanks for Reporting that Issue, i will have a look at it. it might take me a while because im in the middle of a move (and have a lot of other thinks on my mind right now)

**Comment by wolffc** [comment]
Fixed in Version 1.1
I Added a T (Trust issues) and M (Missmatch) Logo.
