### ISSUE TITLE
When a site hasn't been scanned, clicking on the SSL Grade icon should start a scan

### ISSUE THREAD

**Issue by ihatecsv** [wolffc/sslgrade-chrome#5]
Instead of opening the SSL Grade menu, clicking on a site with a "No" icon should start a scan for that site in a new tab.

Thoughts?

**Comment by wolffc** [comment]
good point the "No" usally means that there is No SSL. because you are on an HTTP URL. 
klicking on it should start an scan for the current domain. but it currently only submits "HTTP:" instad of domain name. 

I consider This an Bug. an will Try to fix it soon.

**Comment by wolffc** [comment]
issu is fixed in version 1.1.1 by even scanning HTTP urls domain if you click on the "No" icon.
