### ISSUE TITLE
No longer available in the chrome store

### ISSUE THREAD

**Issue by Dr-Flay** [wolffc/sslgrade-chrome#6]
Is there any chance you will be resubmitting the extension ?

**Comment by wolffc** [comment]
thanks for notifying me i missed that the store now requires "screenshots" for your extension to be listed.

i have now republished the extension.

**Comment by Dr-Flay** [comment]
Excellent.
I installed Edge Beta (chromium) and couldn't find the extension anymore.

**Comment by C0rn3j** [comment]
This can be closed.

**Comment by wolffc** [comment]
Thanks @C0rn3j
